name: "[internal] publish all packages"

on:
  workflow_call:
    inputs:
      mode:
        type: string
        description: supporte values are 'release' and 'dry-run'
        required: true

jobs:
  publish-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: codegen
          path: ./codegen

      - uses: ./.github/actions/publish-node
        with:
          registry-token: ${{ secrets.NPM_REGISTRY_TOKEN }}
          mode: ${{ inputs.mode }}
